name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test JPEG files
        run: |
          for file in $(find . -name "*.jpg"); do
            if ! file "$file" | grep -q 'JPEG'; then
              echo "Corrupu file: $file"
              cp var/www/html/data/1.jpg "$file" #image au hasard
            fi
          done







     







































             





































